/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9077ae62-6b15-4a06-9b8f-d074a7e4b577 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool light1;
  bool light2;
  bool light3;
  bool light4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int Switch1=18;
const int Switch2=19;
const int Switch3=22;
const int Switch4=23;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  pinMode(Switch1,OUTPUT);
  pinMode(Switch2,OUTPUT);
  pinMode(Switch3,OUTPUT);
  pinMode(Switch4,OUTPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Light1 is READ_WRITE variable, onLight1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight1Change()  {
  // Add your code here to act upon Light1 change
  
  if(light1)
  {
    digitalWrite(Switch1,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(Switch1,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Light2 is READ_WRITE variable, onLight2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight2Change()  {
  // Add your code here to act upon Light2 change
  if(light2)
  {
    digitalWrite(Switch2,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(Switch2,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Light3 is READ_WRITE variable, onLight3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight3Change()  {
  // Add your code here to act upon Light3 change
  if(light3)
  {
    digitalWrite(Switch3,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(Switch3,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Light4 is READ_WRITE variable, onLight4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight4Change()  {
  // Add your code here to act upon Light4 change
  
  if(light4)
  {
    digitalWrite(Switch4,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(Switch4,LOW);
    Serial.println("OFF");
  }
}
